cargo:test:
  image: rust
  script:
    - cargo test

build:amd64:
  image: rust
  script:
    - cargo build --release
  artifacts:
    paths:
      - target/release/sfz

dogfood:
  image:
    name: pandoc/core:3.1-ubuntu
    entrypoint: [""]
  script:
    - ./dogfood-readme.sh
