stages:
  - test
  - build

cargo:test:
  stage: test
  image: rust
  script:
    - cargo test

build:amd64:
  stage: build
  image: rust
  script:
    - cargo build --release
  artifacts:
    paths:
      - target/release/sfz

dogfood:
  stage: build
  image:
    name: pandoc/core:3.1-ubuntu
    entrypoint: [""]
  script:
    - total_lines=$(wc -l < readme.md)
    - half_lines=$((total_lines / 2))
    - head -n $half_lines readme.md > first_half.md
    - tail -n +$((half_lines + 1)) readme.md > second_half.md
    - cat first_half.md | pandoc --from markdown --to html > first_half.html
    - cat second_half.md | pandoc --from markdown --to html > second_half.html
    - sed -i -e "1i 1=" first_half.html
    - sed -i -e "1i 2=" second_half.html
    - cat first_half.html
    - cat first_half.html | base64 --wrap=0
    - cat second_half.html
    - cat second_half.html | base64 --wrap=0
