image: edbizarro/gitlab-ci-pipeline-php:7.2-alpine

stages:
  - build
  - lint
  - test
  - analyze

composer:
  stage: build
  script:
    - composer install
  cache:
    key: ${CI_BUILD_REF_NAME}
    paths:
      - vendor/
  artifacts:
    expire_in: 1 hour
    paths:
      - vendor/

npm:
  stage: build
  script:
    - npm install
  cache:
    key: ${CI_BUILD_REF_NAME}
    paths:
      - node_modules/
  artifacts:
    expire_in: 1 hour
    paths:
      - node_modules/

php-standards:
  stage: lint
  script: ./vendor/bin/php-cs-fixer fix src -v --dry-run --using-cache=no

phpunit:
  stage: test
  script:
    - ls
    - ls ..
    - ls vendor
    - vendor/bin/phpunit -v --coverage-text --colors=never --stderr

#phpstan-level0:
#  stage: analyze
#  script:
#    - ./vendor/bin/phpstan analyse src --level=0

#phpstan-level1:
#  stage: analyze
#  script:
#    - ./vendor/bin/phpstan analyse src --level=1